package crypto

import (
	"crypto/ed25519"
	"fmt"
)

// GenerateEd25519KeyPair generates a long-term Ed25519 signing keypair for device identity.
//
// Mathematical Foundation:
// Ed25519 is an Edwards-curve Digital Signature Algorithm (EdDSA) operating on the twisted Edwards curve:
//
//	-x^2 + y^2 = 1 - (121665/121666) * x^2 * y^2  (mod 2^255 - 19)
//
// Cryptographic Properties:
// 1. High speed and constant-time execution preventing side-channel timing attacks.
// 2. Deterministic Signatures: Nonce 'r' is derived via SHA-512(private_key_prefix || message), preventing catastrophic
//    security failures caused by weak RNGs (such as Sony PS3 ECDSA weak nonce failure).
func GenerateEd25519KeyPair() (ed25519.PublicKey, ed25519.PrivateKey, error) {
	pub, priv, err := ed25519.GenerateKey(nil)
	if err != nil {
		return nil, nil, fmt.Errorf("ed25519: failed to generate identity keypair: %w", err)
	}
	return pub, priv, nil
}

// SignMessage creates a 64-byte Ed25519 signature over a message using the sender's private identity key.
//
// Mathematical Signature Construction:
// Signature sigma = (R, S) where:
//
//	R = r * G  (r is deterministic scalar derived from SHA-512 of private key + message)
//	k = SHA-512(R || Public_Key || Message)  (mod L)
//	S = (r + k * private_scalar)  (mod L)
func SignMessage(priv ed25519.PrivateKey, message []byte) ([]byte, error) {
	if len(priv) != ed25519.PrivateKeySize {
		return nil, fmt.Errorf("ed25519: invalid private key size %d, expected %d", len(priv), ed25519.PrivateKeySize)
	}
	sig := ed25519.Sign(priv, message)
	return sig, nil
}

// VerifySignature checks if a 64-byte signature is valid for a message under the given Ed25519 public key.
//
// Verification Mechanics:
// Verify computes k = SHA-512(R || Public_Key || Message) and checks if:
//
//	S * G == R + k * Public_Key
//
// If equal, the signature is mathematically proven to be generated by the owner of the private identity key.
func VerifySignature(pub ed25519.PublicKey, message []byte, signature []byte) bool {
	if len(pub) != ed25519.PublicKeySize || len(signature) != ed25519.SignatureSize {
		return false
	}
	return ed25519.Verify(pub, message, signature)
}
